# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_field', '0002_auto_20150119_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_choices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[(b't', b'Text'), (b'a', b'Large Text Field'), (b'i', b'Integer'), (b'f', b'Floating point decimal'), (b'b', b'Boolean (Yes/No)'), (b'm', b'Dropdown Choices'), (b'd', b'Date'), (b'h', b'Date Time')], default=b't', max_length=1),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
