# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_field', '0003_auto_20170322_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
